既存アカウントの登録挙動
chicobami/duorange pull request #14
Opened 2024-03-25 06:30 UTC by chicobami

## topic
クエスト1にて
メールアドレス, パスワード入力後「登録」押下
→すでに登録済みのアカウント情報だった場合の挙動仮実装

## attention
挙動確認用に2つセリフ行を増やしています
アカウント登録の有無は既存実装内で行えているためアラート表現の変更とその後のスライド表示先のイメージを追加していますが
他に相応しい実装方法があれば適宜変更いただいて構いません🙇！

### テスト挙動
https://github.com/chicobami/duorange/assets/58246272/5466c1df-bf2f-467d-bc82-3500989e1448

2024-03-25 06:31 UTC, chicobami commented on src/components/pages/Quest1View.vue
> +		  { id: 29, text: 'ではログインしてみよう' }, // NOTE: 同一アカウントが存在する場合の動作確認用, セリフは適当です
27, 28, 29が一緒に出現中です
68行目の記述方法修正お願いしたいです…🙇！

2024-03-25 20:32 UTC, erikka-22 requested changes
27, 28, 29 が一緒に出現する件、修正希望をコメントいたしました！

2024-03-25 20:32 UTC, erikka-22 commented on src/components/pages/Quest1View.vue
> +        this.slideToShow = 28; // TODO: 正しい表示に改修
```
this.currentSlideStart = 28
```

に改修お願いします！

2024-03-25 23:30 UTC, chicobami commented on src/components/pages/Quest1View.vue
> +        this.slideToShow = 28; // TODO: 正しい表示に改修
@erikka-22 
dc9e5238fde936c078153cdad7583b20c5780901
ご提示いただいた内容でネコサイバー仙人とセリフが吹っ飛ぶ状態だったので
`=+`で表示先idの加算を行ったところ意図通りの遷移となりました！
改めてこの状態でご確認をいただけますと幸いです🙇！

2024-03-26 13:22 UTC, erikka-22 commented on src/components/pages/Quest1View.vue
> +        this.slideToShow = 28; // TODO: 正しい表示に改修
@chicobami 
修正ありがとうございます！

ちえさんに修正していただいたソースをgit pull して動かしてみたところ、登録済みメールアドレスとパスワードを入力すると、スライド4に飛びました。

```
this.currentSlideStart += 3;
```
で、登録済みメールアドレスとパスワードを入力した後、スライド25からスライド28に飛ぶという期待した動作になりましたがいかがでしょうか...？

期待する挙動の認識を私が間違えている可能性が大いにあるので、教えていただけるとありがたいです！

2024-03-26 23:06 UTC, chicobami commented on src/components/pages/Quest1View.vue
> +        this.slideToShow = 28; // TODO: 正しい表示に改修
@erikka-22 
大変失礼しました！私のテスト時のミス（1〜22をコメントアウトしてテスト実行）でid4に飛んでました…
163f523f186ec06485034ebb8708245dc407340c
こちらで修正いたしました！！！

2024-03-26 23:42 UTC, chicobami commented on src/components/pages/Quest1View.vue
>  			}
新規のアカウント登録後、27で終了せず28, 29の表示も有効となるため、
27でendのパターンを追加しています
```
{ id: 27, text: '最後に、最初の画面に戻ってこのサイトにログインだ！' },
{ id: 28, text: 'おや、アカウントはすでに作成しているのだな！' },
{ id: 29, text: 'ではログインしてみよう' },
```

条件を「id === 27 || id === 29」の方がシンプルでしょうか？？

2024-03-27 10:32 UTC, erikka-22 commented on src/components/pages/Quest1View.vue
>  			}
ありがとうございます！
これでよいかと思います！

2024-03-27 10:33 UTC, erikka-22 commented on src/components/pages/Quest1View.vue
> +        this.slideToShow = 28; // TODO: 正しい表示に改修
@chicobami 
ありがとうございます！
LGTMです！

2024-03-27 10:34 UTC, erikka-22 approved these changes

2024-03-27 10:34 UTC, erikka-22 commented
LGTM!

2024-03-27 13:58 UTC, merged